# Generated by Django 4.2 on 2025-11-02 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_ingresoproducto_remove_producto_precio_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
    ]
