# Generated by Django 4.2 on 2025-11-02 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_producto_precio_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleingresoproducto',
            name='precio_unitario',
        ),
    ]
