# Generated by Django 4.2 on 2025-11-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_detalleingresoproducto_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleingresoproducto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleingresoproducto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
