# Generated by Django 4.2 on 2025-11-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_producto_precio_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
